language: node_js
node_js:
  - "10"
  - node

script:
  - yarn install
  - yarn build
  - yarn test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn build && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
